development:
  host: localhost
  database: speakeasy_cheque_development

test:
  host: localhost
  database: speakeasy_cheque_test

# set these environment variables on your prod server
production:
  host: localhost
  database: speakeasy_cheque_production

  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
